### ISSUE TITLE
Unexpected character '@'  (from UglifyJs)

### ISSUE THREAD

**Issue by theKashey** [ai/size-limit#79]
Look like it's time to deprecate UglifyJs and move to https://github.com/terser-js/terser

It's easy to reproduce the problem - just ignore `@babel/runtime` in `.size-limit`
```js
[
  {
    path: "dist/es2015/index.js",
    limit: "5 KB",
    ignore: ["prop-types","@babel/runtime"]
  }
]
```

**Comment by ai** [comment]
Good idea. Do you want to send PR?

**Comment by theKashey** [comment]
If you are ok with terser - then yes

**Comment by ai** [comment]
Yeap. If `uglify-es` is dead we need to replace it.

**Comment by ai** [comment]
Webpack moved to Tenser. Seems like issue was fixed.

**Comment by theKashey** [comment]
Yep, was just going to mention it. But should size-limit bump the package version?

**Comment by ai** [comment]
I use `^` in dependencies, so I think we shouldn’t.

**Comment by bpierre** [comment]
I still get this bug with a fresh install, with either yarn or npm.

**Comment by ai** [comment]
Open new issue with full details on the error
